// Power BI DAX measures for the Community Energy Flex dashboard.
// Written per the dax-optimization guidance: VAR for shared sub-expressions,
// DIVIDE for safe division, SUM for task counts, explicit BLANK handling.
// Model: fct_daily_savings (fact) related to dim_date / dim_device /
// dim_community by their integer surrogate keys (single-direction filters).
//
// After pasting each measure, set its format string (Measure tools ribbon):
// the "Format:" note above each measure gives the intended string. Also set
// dim_date[day_name] to Sort by column = day_of_week (Column tools).

// --- Conditional planning differences --------------------------------------
// These measures are planning comparisons against the explicit preferred start.
// They exclude non-reportable rows and must never be presented as realised savings.

// Format: £#,##0.00
Conditional Cost Difference (GBP) =
DIVIDE (
    CALCULATE (
        SUM ( fct_daily_savings[reported_cost_saving_p] ),
        KEEPFILTERS ( fct_daily_savings[reporting_status] = "reportable" )
    ),
    100
)

// Format: #,##0.00 "kg"
Conditional Carbon Difference (kg) =
DIVIDE (
    CALCULATE (
        SUM ( fct_daily_savings[reported_carbon_saving_g] ),
        KEEPFILTERS ( fct_daily_savings[reporting_status] = "reportable" )
    ),
    1000
)

// Format: #,##0
Peak Slots Avoided =
CALCULATE (
    SUM ( fct_daily_savings[reported_peak_slots_avoided] ),
    KEEPFILTERS ( fct_daily_savings[reporting_status] = "reportable" )
)

// Format: #,##0
Tasks Planned =
CALCULATE (
    SUM ( fct_daily_savings[source_task_count] ),
    KEEPFILTERS ( fct_daily_savings[reporting_status] = "reportable" )
)

// Format: #,##0
Households Participating =
CALCULATE (
    DISTINCTCOUNT ( fct_daily_savings[household_id] ),
    KEEPFILTERS ( fct_daily_savings[reporting_status] = "reportable" )
)

// Format: 0.00
Avg Recommendation Robustness =
CALCULATE (
    AVERAGE ( fct_daily_savings[robustness_score] ),
    KEEPFILTERS ( fct_daily_savings[reporting_status] = "reportable" )
)

// --- Ratio: safe division against the baseline ------------------------------

// Returns BLANK when there is no baseline - never a #DIV/0.
// Format: 0.0%
Conditional Cost Difference % =
VAR SavingP = CALCULATE (
    SUM ( fct_daily_savings[reported_cost_saving_p] ),
    KEEPFILTERS ( fct_daily_savings[reporting_status] = "reportable" )
)
VAR BaselineP = SUM ( fct_daily_savings[baseline_cost_p] )
RETURN
    DIVIDE ( SavingP, BaselineP )

// --- Time intelligence: month-over-month (the slow-when-sliced case) --------

// Returns BLANK in the first period, by design.
// Format: +0.0%;-0.0%
Conditional Cost Difference (GBP) MoM % =
VAR CurrentSaving = [Conditional Cost Difference (GBP)]
VAR PriorSaving =
    CALCULATE (
        [Conditional Cost Difference (GBP)],
        DATEADD ( dim_date[full_date], -1, MONTH )
    )
RETURN
    DIVIDE ( CurrentSaving - PriorSaving, PriorSaving )

// --- Robustness-gated conditional difference -------------------------------

// Format: £#,##0.00
Robust Conditional Cost Difference (GBP) =
CALCULATE (
    [Conditional Cost Difference (GBP)],
    KEEPFILTERS ( fct_daily_savings[robustness_score] >= 0.5 )
)

// Share of the conditional difference that rests on Strong/Mixed robustness
// indicators. Returns BLANK when there is no conditional difference.
// Format: 0.0%
Robust Conditional Difference % =
DIVIDE ( [Robust Conditional Cost Difference (GBP)], [Conditional Cost Difference (GBP)] )
