name: dbt_energy
version: 0.1.0
config-version: 2
profile: dbt_energy

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_energy:
    staging:
      +materialized: view
    marts:
      +materialized: table
